#!/usr/bin/env bash

OS=$(uname -s)

case $OS in
	Darwin)
		ESC="\x1B["
		;;
	*)
		ESC="\033["
		;;
esac

BLACK="${ESC}0;30m"
BLUE="${ESC}0;34m"
GREEN="${ESC}0;32m"
CYAN="${ESC}0;36m"
RED="${ESC}0;31m"
PURPLE="${ESC}0;35m"
ORANGE="${ESC}0;33m"
LGRAY="${ESC}0;37m"
DGRAY="${ESC}1;30m"
LBLUE="${ESC}1;34m"
LGREEN="${ESC}1;32m"
LCYAN="${ESC}1;36m"
LRED="${ESC}1;31m"
LPURPLE="${ESC}1;35m"
YELLOW="${ESC}1;33m"
WHITE="${ESC}1;37m"
NC="${ESC}0m"

# vim: set ts=2 sw=2 tw=0 ft=sh et :
